export const TOPIC_QUERY = [
  'embodied AI',
  'embodied intelligence',
  'robot learning',
  'robotics manipulation',
  'humanoid robot',
  'world model robotics',
  'imitation learning robotics',
  'vision-language-action',
  'VLM for robotics',
  'reinforcement learning for robotics',
  'robot locomotion control',
  'teleoperation robotics',
  'visual language navigation',
  'VLN robotics',
  'semantic SLAM',
  'distributed SLAM',
  'multi-sensor fusion localization',
  'underwater robotics',
  'AUV robotics',
  'ROV robotics',
].join(' OR ');
